name: "Test"
on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "30 17 * * *" # build at 17:00 UTC every day
                          # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: install nix
      uses: cachix/install-nix-action@v27
      #with:
      #github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#iso
    - run: ls

    - name: Upload ISO as artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
