name: "Build ISO"
on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "30 17 * * *" # build at 17:00 UTC every day
                          # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: install nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: nix flake checker
      uses: DeterminateSystems/flake-checker-action@main
      #with:
      #github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#iso
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.BUILD_SECRET }}
        file: ./result/iso/*.iso
        asset_name: ${{ github.workflow }}-${{ github.ref || github.run_id }}
        tag: ${{ github.ref }}
        overwrite: true
        #file_glob: true

